/**
 * JanVikas AI — Complete Indian Administrative Location Database (2026 Edition)
 * Reference: Census of India & Ministry of Home Affairs Official Gazetteers
 * Structure: State/UT -> District -> Cities/Towns Array
 */

export const locationData = {
  "Andhra Pradesh": {
    "Alluri Sitharama Raju": ["Paderu", "Araku Valley", "Chintapalli", "Rampachodavaram"],
    "Anakapalli": ["Anakapalli", "Chodavaram", "Narsipatnam", "Yellamanchili"],
    "Ananthapuramu": ["Anantapur", "Dharmavaram", "Gooty", "Tadipatri", "Guntakal"],
    "Annamayya": ["Rayachoti", "Madanapalle", "Rajampet"],
    "Bapatla": ["Bapatla", "Chirala", "Repalle"],
    "Chittoor": ["Chittoor", "Kuppam", "Palamaner"],
    "East Godavari": ["Rajahmundry", "Kovvur", "Nidadavole"],
    "Eluru": ["Eluru", "Jangareddygudem", "Nuzvid"],
    "Guntur": ["Guntur", "Tenali", "Mangalagiri", "Tadikonda"],
    "Kakinada": ["Kakinada", "Tuni", "Pithapuram", "Samalkot"],
    "Konaseema": ["Amalapuram", "Ravulapalem", "Ramachandrapuram"],
    "Krishna": ["Machilipatnam", "Gudivada", "Vuyyuru", "Pamarru"],
    "Kurnool": ["Kurnool", "Adoni", "Yemmiganur", "Kodumur"],
    "Nandyal": ["Nandyal", "Allagadda", "Dhone", "Nandikotkur"],
    "NTR": ["Vijayawada", "Kanchikacherla", "Tiruvuru", "Ibrahimpatnam"],
    "Palnadu": ["Narasaraopet", "Piduguralla", "Sattenapalli", "Chilakaluripet"],
    "Parvathipuram Manyam": ["Parvathipuram", "Salur"],
    "Prakasam": ["Ongole", "Markapur", "Kanigiri", "Kandukur"],
    "Srikakulam": ["Srikakulam", "Palasa-Kasibugga", "Amadalavalasa", "Ichchapuram"],
    "Sri Potti Sriramulu Nellore": ["Nellore", "Kavali", "Gudur", "Atmakur"],
    "Sri Sathya Sai": ["Puttaparthi", "Hindupur", "Kadiri", "Penukonda"],
    "Tirupati": ["Tirupati", "Srikalahasti", "Venkatagiri", "Sullurpeta"],
    "Visakhapatnam": ["Visakhapatnam", "Gajuwaka", "Bheemunipatnam", "Anakapalle"],
    "Vizianagaram": ["Vizianagaram", "Bobbili", "Cheepurupalli", "Gajapathinagaram"],
    "West Godavari": ["Bhimavaram", "Narasapuram", "Tadepalligudem", "Tanuku"],
    "YSR Kadapa": ["Kadapa", "Proddatur", "Pulivendula", "Badvel", "Jammalamadugu"]
  },
  "Arunachal Pradesh": {
    "Anjaw": ["Hawai", "Hayuliang", "Chaglagam"],
    "Changlang": ["Changlang", "Miao", "Jairampur", "Bordumsa"],
    "East Kameng": ["Seppa", "Chayangtajo", "Pipili"],
    "East Siang": ["Pasighat", "Ruksin", "Mebo"],
    "Itanagar Capital Complex": ["Itanagar", "Naharlagun", "Nirjuli", "Banderdewa"],
    "Kamle": ["Raga", "Kamporijo"],
    "Kra Daadi": ["Palin", "Tali", "Chambang"],
    "Kurung Kumey": ["Koloriang", "Sangram", "Nyapin"],
    "Leparada": ["Basar", "Tirbin", "Sago"],
    "Lohit": ["Tezu", "Sunpura", "Wakro"],
    "Longding": ["Longding", "Pangchao", "Kanubari"],
    "Lower Dibang Valley": ["Anini", "Roing", "Dambuk"],
    "Lower Subansiri": ["Ziro", "Yachuli", "Pistana"],
    "Namsai": ["Namsai", "Chowkham", "Mahadevpur"],
    "Pakke Kessang": ["Lemmi", "Seijosa", "Pakke-Kessang"],
    "Papum Pare": ["Yupia", "Doimukh", "Sagalee", "Kimim"],
    "Shi Yomi": ["Tato", "Mechuka", "Monigong"],
    "Siang": ["Boleng", "Pangin", "Rumgong"],
    "Tawang": ["Tawang", "Lumla", "Jang"],
    "Tirap": ["Khonsa", "Deomali", "Lazu"],
    "Upper Dibang Valley": ["Anini", "Etalin", "Mypi"],
    "Upper Siang": ["Yingkiong", "Tuting", "Mariyang"],
    "Upper Subansiri": ["Daporijo", "Dumporijo", "Nacho"],
    "West Kameng": ["Bomdila", "Dirang", "Rupa", "Singchung"],
    "West Siang": ["Aalo", "Likabali", "Garru"]
  },
  "Assam": {
    "Bajali": ["Pathsala", "Sarthebari"],
    "Baksa": ["Mushalpur", "Salbari", "Barama"],
    "Barpeta": ["Barpeta", "Howly", "Barpeta Road"],
    "Biswanath": ["Biswanath Chariali", "Gohpur"],
    "Bongaigaon": ["Bongaigaon", "Abhayapuri", "Merchar"],
    "Cachar": ["Silchar", "Lakhipur", "Sonai"],
    "Charaideo": ["Sonari", "Moranhat"],
    "Chirang": ["Kajalgaon", "Bijni"],
    "Darrang": ["Mangaldai", "Sipajhar", "Kharupetia"],
    "Dhemaji": ["Dhemaji", "Jonai", "Silapathar"],
    "Dhubri": ["Dhubri", "Gauripur", "Bilasipara"],
    "Dibrugarh": ["Dibrugarh", "Chabua", "Tingkhong", "Naharkatia"],
    "Dima Hasao": ["Haflong", "Maibang", "Umrongso"],
    "Goalpara": ["Goalpara", "Lakhipur", "Dudhnai"],
    "Golaghat": ["Golaghat", "Bokakhat", "Dergaon", "Sarupathar"],
    "Hailakandi": ["Hailakandi", "Lala", "Algapur"],
    "Hojai": ["Hojai", "Lanka", "Lumding"],
    "Jorhat": ["Jorhat", "Mariani", "Teok", "Titabor"],
    "Kamrup": ["Amingaon", "Rangia", "Hajo", "Boko"],
    "Kamrup Metropolitan": ["Guwahati", "Dispur", "Azara", "Chandrapur"],
    "Karbi Anglong": ["Diphu", "Howraghat", "Dokmoka"],
    "Karimganj": ["Karimganj", "Badarpur", "Patharkandi"],
    "Kokrajhar": ["Kokrajhar", "Gossaigaon", "Fakiragram"],
    "Lakhimpur": ["North Lakhimpur", "Bihpuria", "Dhakuakhana"],
    "Majuli": ["Garamur", "Kamalabari", "Jengraimukh"],
    "Morigaon": ["Morigaon", "Jagiroad", "Bhuragaon"],
    "Nagaon": ["Nagaon", "Dhing", "Kaliabor", "Raha"],
    "Nalbari": ["Nalbari", "Tihu", "Mukalmua"],
    "Sivasagar": ["Sivasagar", "Nazira", "Amguri"],
    "Sonitpur": ["Tezpur", "Dhekiajuli", "Rangapara"],
    "South Salmara-Mankachar": ["Hatsingimari", "Mankachar"],
    "Tinsukia": ["Tinsukia", "Digboi", "Margherita", "Doomdooma"],
    "Udalguri": ["Udalguri", "Tangla", "Bhairabkunda"],
    "West Karbi Anglong": ["Hamren", "Donkamokam"]
  },
  "Bihar": {
    "Araria": ["Araria", "Forbesganj", "Jogbani"],
    "Arwal": ["Arwal", "Kurtha"],
    "Aurangabad": ["Aurangabad", "Rafiganj", "Nabinagar", "Daudnagar"],
    "Banka": ["Banka", "Amarpur", "Katoria"],
    "Begusarai": ["Begusarai", "Barauni", "Teghra", "Ballia"],
    "Bhagalpur": ["Bhagalpur", "Sultanganj", "Kahalgon", "Naugachhia"],
    "Bhojpur": ["Arrah", "Jagdishpur", "Piro", "Behea"],
    "Buxar": ["Buxar", "Dumraon", "Chausa"],
    "Darbhanga": ["Darbhanga", "Benipur", "Baheri"],
    "East Champaran": ["Motihari", "Raxaul", "Dhaka", "Areraj"],
    "Gaya": ["Gaya", "Bodhgaya", "Sherghati", "Tekari"],
    "Gopalganj": ["Gopalganj", "Barauli", "Mirganj"],
    "Jamui": ["Jamui", "Jhajha", "Gidhaur"],
    "Jehanabad": ["Jehanabad", "Makhdumpur"],
    "Kaimur": ["Bhabua", "Mohania", "Ramgarh"],
    "Katihar": ["Katihar", "Manihari", "Barsoi"],
    "Khagaria": ["Khagaria", "Gogri Jamaalpur"],
    "Kishanganj": ["Kishanganj", "Bahadurganj", "Thakurganj"],
    "Lakhisarai": ["Lakhisarai", "Barahiya"],
    "Madhepura": ["Madhepura", "Murliganj", "Singheshwar"],
    "Madhubani": ["Madhubani", "Jainagar", "Jhanjharpur", "Benipatti"],
    "Munger": ["Munger", "Jamalpur", "Haveli Kharagpur"],
    "Muzaffarpur": ["Muzaffarpur", "Kanti", "Motipur", "Baruraj"],
    "Nalanda": ["Bihar Sharif", "Rajgir", "Hilsa", "Harnaut"],
    "Nawada": ["Nawada", "Hisua", "Rajauli"],
    "Patna": ["Patna", "Danapur", "Khagaul", "Fatuha", "Mokama", "Barh", "Masaurhi"],
    "Purnia": ["Purnia", "Banmankhi", "Kasba", "Dhamdaha"],
    "Rohtas": ["Sasaram", "Dehri", "Bikramganj", "Nokha"],
    "Saharsa": ["Saharsa", "Simri Bakhtiyarpur"],
    "Samastipur": ["Samastipur", "Dalsinghsarai", "Rosera", "Tajpur"],
    "Saran": ["Chhapra", "Sonepur", "Marhaura"],
    "Sheikhpura": ["Sheikhpura", "Barbigha"],
    "Sheohar": ["Sheohar"],
    "Sitamarhi": ["Sitamarhi", "Bairgania", "Pupri"],
    "Siwan": ["Siwan", "Maharajganj", "Mairwa"],
    "Supaul": ["Supaul", "Birpur", "Triveniganj"],
    "Vaishali": ["Hajipur", "Mahnar", "Lalganj", "Bidupur"],
    "West Champaran": ["Bettiah", "Bagaha", "Narkatiaganj", "Ramnagar"]
  },
  "Chhattisgarh": {
    "Balod": ["Balod", "Dalli Rajhara", "Gunderdehi"],
    "Baloda Bazar": ["Baloda Bazar", "Bhatapara", "Kasdol", "Simga"],
    "Balrampur": ["Balrampur", "Ramanujganj", "Wadrafnagar"],
    "Bastar": ["Jagdalpur", "Bastanar", "Tokapal"],
    "Bemetara": ["Bemetara", "Saja", "Nawagarh"],
    "Bijapur": ["Bijapur", "Bhairamgarh"],
    "Bilaspur": ["Bilaspur", "Kota", "Bilha", "Takahatpur"],
    "Dantewada": ["Dantewada", "Kirandul", "Bacheli", "Geedam"],
    "Dhamtari": ["Dhamtari", "Kurud", "Nagri"],
    "Durg": ["Durg", "Bhilai Nagar", "Patan", "Kumhari"],
    "Gariaband": ["Gariaband", "Rajim", "Deobhog"],
    "Gaurela-Pendra-Marwahi": ["Pendra", "Gaurela", "Marwahi"],
    "Janjgir-Champa": ["Janjgir", "Champa", "Naila Janjgir", "Akaltara"],
    "Jashpur": ["Jashpur Nagar", "Pathalgaon", "Kunkuri"],
    "Kabirdham": ["Kawardha", "Pandariya", "Bodla"],
    "Kanker": ["Kanker", "Charama", "Bhanupratappur"],
    "Khairagarh-Chhuikhadan-Gandai": ["Khairagarh", "Chhuikhadan", "Gandai"],
    "Kondagaon": ["Kondagaon", "Farashgaon", "Keshkal"],
    "Korba": ["Korba", "Katghora", "Pali", "Champa"],
    "Koriya": ["Baikunthpur", "Sonhat"],
    "Mahasamund": ["Mahasamund", "Bagbahra", "Saraipali", "Pithora"],
    "Manendragarh-Chirmiri-Bharatpur": ["Manendragarh", "Chirmiri", "Bharatpur"],
    "Mohla-Manpur-Ambagarh Chowki": ["Mohla", "Manpur", "Ambagarh Chowki"],
    "Mungeli": ["Mungeli", "Lormi", "Pathariya"],
    "Narayanpur": ["Narayanpur", "Orchha"],
    "Raigarh": ["Raigarh", "Kharsia", "Gharghoda", "Dharamjaigarh"],
    "Raipur": ["Raipur", "Arang", "Abhanpur", "Tilda Newra"],
    "Rajnandgaon": ["Rajnandgaon", "Dongargarh", "Chhuikhadan"],
    "Sakti": ["Sakti", "Dabhra", "Malkharoda"],
    "Sarangarh-Bilaigarh": ["Sarangarh", "Bilaigarh"],
    "Sukma": ["Sukma", "Konta", "Chhindgarh"],
    "Surajpur": ["Surajpur", "Pratappur", "Bhaiyathan"],
    "Surguja": ["Ambikapur", "Sitapur", "Lakhanpur"]
  },
  "Goa": {
    "North Goa": ["Panaji", "Mapusa", "Bicholim", "Valpoi", "Ponda"],
    "South Goa": ["Margao", "Vasco da Gama", "Mormugao", "Quepem", "Curchorem", "Canacona"]
  },
  "Gujarat": {
    "Ahmedabad": ["Ahmedabad", "Sanand", "Viramgam", "Dholka", "Bavla"],
    "Amreli": ["Amreli", "Bagasara", "Babra", "Rajula", "Jafrabad"],
    "Anand": ["Anand", "Nadiad", "Khambhat", "Petlad", "Borsad"],
    "Aravalli": ["Modasa", "Bayad", "Dhansura"],
    "Banaskantha": ["Palanpur", "Deesa", "Tharad", "Dhanera", "Radhanpur"],
    "Bharuch": ["Bharuch", "Ankleshwar", "Jambusar", "Zagadia"],
    "Bhavnagar": ["Bhavnagar", "Palitana", "Mahuva", "Talaja", "Vallabhipur"],
    "Botad": ["Botad", "Gadhada", "Barwala"],
    "Chhota Udaipur": ["Chhota Udaipur", "Bodeli", "Jetpur Pavi"],
    "Dahod": ["Dahod", "Devgadh Baria", "Limkheda"],
    "Dang": ["Ahwa", "Saputara", "Subir"],
    "Devbhumi Dwarka": ["Khambhalia", "Dwarka", "Okha", "Ravals"],
    "Gandhinagar": ["Gandhinagar", "Kalol", "Dahegam", "Mansa"],
    "Gir Somnath": ["Veraval", "Somnath", "Talala", "Una", "Kodinar"],
    "Jamnagar": ["Jamnagar", "Dhrol", "Jodiya", "Kalavad"],
    "Junagadh": ["Junagadh", "Keshod", "Mangrol", "Manavadar", "Visavadar"],
    "Kheda": ["Nadiad", "Kheda", "Kapadvanj", "Balasinor", "Dakor"],
    "Kutch": ["Bhuj", "Gandhidham", "Anjar", "Mandvi", "Mundra", "Bhachau"],
    "Mahisagar": ["Lunawada", "Santrampur", "Kadana"],
    "Mehsana": ["Mehsana", "Visnagar", "Kadi", "Unjha", "Vadnagar"],
    "Morbi": ["Morbi", "Wankaner", "Halvad", "Tankara"],
    "Narmada": ["Rajpipla", "Dediyapada", "Sagbara"],
    "Navsari": ["Navsari", "Chikhli", "Gandevi", "Vansda"],
    "Panchmahal": ["Godhra", "Halol", "Kalol", "Shehra"],
    "Patan": ["Patan", "Sidhpur", "Harij", "Chanasma"],
    "Porbandar": ["Porbandar", "Ranavav", "Kutiyana"],
    "Rajkot": ["Rajkot", "Jetpur", "Gondal", "Morbi", "Dhoraji", "Upleta"],
    "Sabarkantha": ["Himatnagar", "Idar", "Prantij", "Khedbrahma"],
    "Surat": ["Surat", "Bardoli", "Vyara", "Sayan", "Kadod"],
    "Surendranagar": ["Surendranagar", "Wadhwan", "Limbdi", "Dhrangadhra"],
    "Tapi": ["Vyara", "Songadh", "Valod"],
    "Vadodara": ["Vadodara", "Dabhoi", "Karjan", "Padra", "Savli"],
    "Valsad": ["Valsad", "Vapi", "Umbergaon", "Pardi", "Dharampur"]
  },
  "Haryana": {
    "Ambala": ["Ambala Cantt", "Ambala City", "Naraingarh"],
    "Bhiwani": ["Bhiwani", "Toshani", "Loharu", "Bawani Khera"],
    "Charkhi Dadri": ["Charkhi Dadri", "Badhra"],
    "Faridabad": ["Faridabad", "Ballabhgarh", "Tigaon"],
    "Fatehabad": ["Fatehabad", "Tohana", "Ratia", "Bhattukalan"],
    "Gurugram": ["Gurugram", "Sohna", "Pataudi", "Farrukhnagar"],
    "Hisar": ["Hisar", "Hansi", "Uklanamandi", "Barwala"],
    "Jhajjar": ["Jhajjar", "Bahadurgarh", "Beri"],
    "Jind": ["Jind", "Narwana", "Safidon", "Uchana"],
    "Kaithal": ["Kaithal", "Pundri", "Kalayat", "Guhla"],
    "Karnal": ["Karnal", "Gharaunda", "Indri", "Assandh"],
    "Kurukshetra": ["Thanesar", "Shahbad", "Pehowa", "Ladwa"],
    "Mahendragarh": ["Narnaul", "Mahendragarh", "Kanina"],
    "Nuh": ["Nuh", "Ferozepur Jhirka", "Taoru", "Punahana"],
    "Palwal": ["Palwal", "Hathin", "Hodal"],
    "Panchkula": ["Panchkula", "Kalka", "Pinjore Raipur"],
    "Panipat": ["Panipat", "Samalkha", "Israna"],
    "Rewari": ["Rewari", "Bawal", "Dharuhera"],
    "Rohtak": ["Rohtak", "Meham", "Kalanaur"],
    "Sirsa": ["Sirsa", "Dabwali", "Ellenabad", "Rania"],
    "Sonipat": ["Sonipat", "Gohana", "Ganaur", "Kharkhoda"],
    "Yamunanagar": ["Yamunanagar", "Jagadhri", "Radaur", "Chhachhrauli"]
  },
  "Himachal Pradesh": {
    "Bilaspur": ["Bilaspur", "Ghumarwin", "Shree Naina Devi Ji"],
    "Chamba": ["Chamba", "Dalhousie", "Chowari", "Pangi"],
    "Hamirpur": ["Hamirpur", "Nadaun", "Sujanpur Tira", "Bhoranj"],
    "Kangra": ["Dharamshala", "Kangra", "Palampur", "Nurpur", "Dehra"],
    "Kinnaur": ["Recong Peo", "Kalpa", "Sangla", "Pooh"],
    "Kullu": ["Kullu", "Manali", "Anni", "Banjar"],
    "Lahaul and Spiti": ["Keylong", "Kaza", "Udaipur"],
    "Mandi": ["Mandi", "Sundernagar", "Sarkaghat", "Jogindernagar"],
    "Shimla": ["Shimla", "Rampur Bushahr", "Theog", "Rohru", "Chopal"],
    "Sirmour": ["Nahan", "Paonta Sahib", "Rajgarh", "Sarahan"],
    "Solan": ["Solan", "Baddi", "Nalagarh", "Kasauli", "Arki"],
    "Una": ["Una", "Amb", "Haroli", "Mehatpur"]
  },
  "Jharkhand": {
    "Bokaro": ["Bokaro Steel City", "Chas", "Bermo", "Tenughat"],
    "Chatra": ["Chatra", "Tandwa", "Hunterganj"],
    "Deoghar": ["Deoghar", "Madhupur", "Jasidih"],
    "Dhanbad": ["Dhanbad", "Jharia", "Sindri", "Katras", "Nirsa"],
    "Dumka": ["Dumka", "Jarmundi", "Basukinath"],
    "East Singhbhum": ["Jamshedpur", "Ghatshila", "Chakulia", "Baharagora"],
    "Garhwa": ["Garhwa", "Nagar Untari", "Ranka"],
    "Giridih": ["Giridih", "Dumri", "Bagodar", "Deori"],
    "Godda": ["Godda", "Mahagama", "Poreyahat"],
    "Gumla": ["Gumla", "Chainpur", "Sisai"],
    "Hazaribagh": ["Hazaribagh", "Barhi", "Barkagaon"],
    "Jamtara": ["Jamtara", "Mihijam", "Kundhit"],
    "Khunti": ["Khunti", "Murhu", "Torpa"],
    "Koderma": ["Jhumri Telaiya", "Koderma", "Domchanch"],
    "Latehar": ["Latehar", "Chandwa", "Mahuadanr"],
    "Lohardaga": ["Lohardaga", "Kisko", "Bhandra"],
    "Pakur": ["Pakur", "Littipara", "Hiranpur"],
    "Palamu": ["Medininagar (Daltonganj)", "Hariharganj", "Lesliganj", "Chhatarpur"],
    "Ramgarh": ["Ramgarh Cantt", "Patratu", "Gola"],
    "Ranchi": ["Ranchi", "Bundu", "Kanke", "Silli", "Ormanjhi"],
    "Sahibganj": ["Sahibganj", "Rajmahal", "Barharwa"],
    "Seraikela Kharsawan": ["Seraikela", "Adityapur", "Chandil"],
    "Simdega": ["Simdega", "Kolebira", "Thethaitanger"],
    "West Singhbhum": ["Chaibasa", "Chakradharpur", "Kiriburu", "Jagannathpur"]
  },
  "Karnataka": {
    "Bagalkot": ["Bagalkot", "Jamkhandi", "Mudhol", "Ilkal", "Badami"],
    "Ballari": ["Ballari", "Siruguppa", "Kampli"],
    "Belagavi": ["Belagavi", "Chikkodi", "Gokak", "Athani", "Bailhongal", "Saundatti"],
    "Bengaluru Rural": ["Doddaballapur", "Devanahalli", "Hosakote", "Nelamangala"],
    "Bengaluru Urban": ["Bengaluru", "Yelahanka", "Kengeri", "Krishnarajapuram", "Anekal"],
    "Bidar": ["Bidar", "Bhalki", "Humnabad", "Basavakalyan"],
    "Chamarajanagar": ["Chamarajanagar", "Kollegal", "Gundlupet"],
    "Chikkaballapur": ["Chikkaballapur", "Chintamani", "Sidlaghatta", "Gauribidanur"],
    "Chikkamagaluru": ["Chikkamagaluru", "Kadur", "Koppa", "Tarikere", "Sringeri"],
    "Chitradurga": ["Chitradurga", "Hiriyur", "Challakere", "Holalkere"],
    "Dakshina Kannada": ["Mangaluru", "Puttur", "Bantwal", "Belthangady", "Sulya"],
    "Davanagere": ["Davanagere", "Harihar", "Honnali", "Channagiri"],
    "Dharwad": ["Hubballi", "Dharwad", "Kalghatgi", "Navalgund"],
    "Gadag": ["Gadag-Betageri", "Lakshmeshwar", "Mundargi", "Nargund"],
    "Hassan": ["Hassan", "Arsikere", "Channarayapatna", "Sakleshpur", "Holenarasipur"],
    "Haveri": ["Haveri", "Ranebennur", "Byadgi", "Shiggaon"],
    "Kalaburagi": ["Kalaburagi", "Shahabad", "Wadi", "Afzalpur", "Aland", "Chincholi"],
    "Kodagu": ["Madikeri", "Virajpet", "Somwarpet"],
    "Kolar": ["Kolar", "Robertsonpet (KGF)", "Bangarapet", "Mulbagal"],
    "Koppal": ["Koppal", "Gangavathi", "Kushtagi", "Yelaburga"],
    "Mandya": ["Mandya", "Maddur", "Malavalli", "Srirangapatna", "Pandavapura"],
    "Mysuru": ["Mysuru", "Nanjangud", "Hunsur", "T Narasipura", "K R Nagar"],
    "Raichur": ["Raichur", "Sindhanur", "Manvi", "Deodurga"],
    "Ramanagara": ["Ramanagara", "Channapatna", "Magadi", "Kanakapura"],
    "Shivamogga": ["Shivamogga", "Bhadravathi", "Sagar", "Shikaripura", "Soraba"],
    "Tumakuru": ["Tumakuru", "Tiptur", "Sira", "Madhugiri", "Kunigal"],
    "Udupi": ["Udupi", "Kundapura", "Karkala"],
    "Uttara Kannada": ["Karwar", "Sirsi", "Dandeli", "Bhatkal", "Kumta", "Haliyal"],
    "Vijayapura": ["Vijayapura", "Indi", "Sindagi", "Muddebihal"],
    "Vijayanagara": ["Hosapete", "Hagaribommanahalli", "Kottur"],
    "Yadgir": ["Yadgir", "Shahpur", "Shorapur"]
  },
  "Kerala": {
    "Alappuzha": ["Alappuzha", "Cherthala", "Kayamkulam", "Mavelikkara", "Chengannur"],
    "Ernakulam": ["Kochi", "Aluva", "Muvattupuzha", "Angamaly", "Perumbavoor", "Kochi Municipal Corp"],
    "Idukki": ["Thodupuzha", "Munnar", "Kattappana", "Adimali"],
    "Kannur": ["Kannur", "Thalassery", "Payyannur", "Taliparamba", "Mattannur"],
    "Kasaragod": ["Kasaragod", "Kanhangad", "Nileshwaram", "Uppala"],
    "Kollam": ["Kollam", "Karunagappally", "Punalur", "Kottarakkara", "Paravur"],
    "Kottayam": ["Kottayam", "Changanassery", "Pala", "Vaikom", "Kanjirappally"],
    "Kozhikode": ["Kozhikode", "Vatakara", "Koyilandy", "Thamarassery"],
    "Malappuram": ["Malappuram", "Manjeri", "Tirur", "Ponnani", "Kottakkal", "Perinthalmanna"],
    "Palakkad": ["Palakkad", "Ottapalam", "Shornur", "Chittur-Thathamangalam", "Mannarkkad"],
    "Pathanamthitta": ["Pathanamthitta", "Adoor", "Thiruvalla", "Mallappally"],
    "Thiruvananthapuram": ["Thiruvananthapuram", "Neyyattinkara", "Attingal", "Nedumangad", "Varkala"],
    "Thrissur": ["Thrissur", "Guruvayur", "Irinjalakuda", "Chalakudy", "Kunnamkulam", "Kodungallur"],
    "Wayanad": ["Kalpetta", "Mananthavady", "Sulthan Bathery"]
  },
  "Madhya Pradesh": {
    "Agar Malwa": ["Agar", "Susner", "Nalkheda"],
    "Alirajpur": ["Alirajpur", "Jobat"],
    "Anuppur": ["Anuppur", "Kotma", "Amlai", "Rajendragram"],
    "Ashoknagar": ["Ashoknagar", "Mungaoli", "Chanderi"],
    "Balaghat": ["Balaghat", "Waraseoni", "Malaj Khand", "Katangi"],
    "Barwani": ["Barwani", "Sendhwa", "Anjad"],
    "Betul": ["Betul", "Multai", "Amla", "Sarni"],
    "Bhind": ["Bhind", "Gohad", "Mehgaon", "Lahar"],
    "Bhopal": ["Bhopal", "Bairagarh", "Berasia"],
    "Burhanpur": ["Burhanpur", "Nepanagar"],
    "Chhatarpur": ["Chhatarpur", "Khajuraho", "Nowgong", "Harpalpur"],
    "Chhindwara": ["Chhindwara", "Parasia", "Junnardeo", "Amarwara"],
    "Damoh": ["Damoh", "Hatta", "Patharia"],
    "Datia": ["Datia", "Bhander", "Seondha"],
    "Dewas": ["Dewas", "Sonkatch", "Bagli", "Hatpipliya"],
    "Dhar": ["Dhar", "Pithampur", "Kukshi", "Manawar", "Badnawar"],
    "Dindori": ["Dindori", "Shahpura"],
    "Guna": ["Guna", "Raghogarh-Vijaypur", "Chachaura", "Aron"],
    "Gwalior": ["Gwalior", "Dabra", "Bhitarwar"],
    "Harda": ["Harda", "Timarni", "Khirkiya"],
    "Indore": ["Indore", "Mhow (Dr. Ambedkar Nagar)", "Depalpur", "Sanwer"],
    "Jabalpur": ["Jabalpur", "Sihora", "Katangi", "Patan"],
    "Jhabua": ["Jhabua", "Petlawad", "Thandla"],
    "Katni": ["Katni", "Murwara", "Vijayraghavgarh"],
    "Khandwa": ["Khandwa", "Harsud", "Mundhi"],
    "Khargone": ["Khargone", "Sanawad", "Barwaha", "Maheshwar"],
    "Maihar": ["Maihar"],
    "Mandla": ["Mandla", "Nainpur", "Bamhani"],
    "Mandsaur": ["Mandsaur", "Bhanpura", "Garoth", "Sitamau"],
    "Mauganj": ["Mauganj", "Hanumana"],
    "Morena": ["Morena", "Ambah", "Porsa", "Joura", "Sabalgarh"],
    "Narmadapuram": ["Narmadapuram", "Itarsi", "Pipariya", "Pachmarhi", "Seoni Malwa"],
    "Narsinghpur": ["Narsinghpur", "Gadarwara", "Kareli", "Gotegaon"],
    "Neemuch": ["Neemuch", "Jawad", "Manasa"],
    "Niwari": ["Niwari", "Orchha", "Prithvipur"],
    "Pandhurna": ["Pandhurna"],
    "Panna": ["Panna", "Devendranagar", "Pawai"],
    "Raisen": ["Raisen", "Mandiideep", "Obedullaganj", "Bareli"],
    "Rajgarh": ["Rajgarh", "Biaora", "Narsinghgarh", "Sarangpur"],
    "Ratlam": ["Ratlam", "Jaora", "Alot", "Sailana"],
    "Rewa": ["Rewa", "Mangawan", "Teonthar"],
    "Sagar": ["Sagar", "Bina-Etawa", "Khurai", "Deori", "Garhakota"],
    "Satna": ["Satna", "Maihar", "Nagod", "Amarpatan"],
    "Sehore": ["Sehore", "Ashta", "Ichhawar", "Budhni"],
    "Seoni": ["Seoni", "Lakhnadon", "Barghat"],
    "Shahdol": ["Shahdol", "Burhar", "Amlai", "Beohari"],
    "Shajapur": ["Shajapur", "Shujalpur", "Kalapipal"],
    "Sheopur": ["Sheopur", "Vijaypur", "Karahal"],
    "Shivpuri": ["Shivpuri", "Karera", "Kolaras", "Pichhore"],
    "Sidhi": ["Sidhi", "Rampur Naikin", "Churhat"],
    "Singrauli": ["Waidhan", "Singrauli", "Deosar"],
    "Tikamgarh": ["Tikamgarh", "Jatara", "Khargapur"],
    "Ujjain": ["Ujjain", "Nagda", "Khachrod", "Mahidpur", "Tarana"],
    "Umaria": ["Umaria", "Birsinghpur Pali", "Nowrozabad"],
    "Vidisha": ["Vidisha", "Ganjbasoda", "Sironj", "Kurwai"]
  },
  "Maharashtra": {
    "Ahmednagar": ["Ahmednagar", "Sangamner", "Shrirampur", "Kopargaon", "Rahuri"],
    "Akola": ["Akola", "Akot", "Balapur", "Murtizapur"],
    "Amravati": ["Amravati", "Achalpur", "Anjangaon", "Warud", "Morshi"],
    "Bhandara": ["Bhandara", "Tumsar", "Pauni", "Sakoli"],
    "Buldhana": ["Buldhana", "Khamgaon", "Malkapur", "Shegaon", "Chikhli"],
    "Chandrapur": ["Chandrapur", "Ballarpur", "Warora", "Bhadravati", "Mul"],
    "Chhatrapati Sambhajinagar": ["Aurangabad", "Vaijapur", "Kannad", "Paithan", "Gangapur"],
    "Dhule": ["Dhule", "Shirpur", "Dondaicha", "Sakri"],
    "Gadchiroli": ["Gadchiroli", "Aheri", "Chamorshi", "Desaiganj"],
    "Gondia": ["Gondia", "Tirora", "Arjuni Morgaon"],
    "Hingoli": ["Hingoli", "Basmath", "Kalamnuri"],
    "Jalgaon": ["Jalgaon", "Bhusawal", "Chalisgaon", "Amalner", "Pachora", "Yawal"],
    "Jalna": ["Jalna", "Ambad", "Bhokardan", "Partur"],
    "Kolhapur": ["Kolhapur", "Ichalkaranji", "Jaysingpur", "Kagal", "Gadhinglaj"],
    "Latur": ["Latur", "Udgir", "Ahmedpur", "Nilanga", "Ausa"],
    "Mumbai City": ["Mumbai", "Colaba", "Dharavi", "Byculla", "Fort"],
    "Mumbai Suburban": ["Bandra", "Andheri", "Kurla", "Borivali", "Ghatkopar"],
    "Nagpur": ["Nagpur", "Kamptee", "Umred", "Katol", "Ramtek"],
    "Nanded": ["Nanded", "Degloor", "Loha", "Mudkhed", "Hadgaon"],
    "Nandurbar": ["Nandurbar", "Shahada", "Taloda", "Navapur"],
    "Nashik": ["Nashik", "Malegaon", "Manmad", "Sinnar", "Yeola", "Igatpuri"],
    "Osmanabad": ["Osmanabad", "Tuljapur", "Omerga", "Bhum"],
    "Palghar": ["Palghar", "Vasai-Virar", "Dahanu", "Jawhar", "Boisar"],
    "Parbhani": ["Parbhani", "Gangakhed", "Selu", "Jintur"],
    "Pune": ["Pune", "Baramati", "Pimpri-Chinchwad", "Lonavala", "Daund", "Shirur", "Talegaon"],
    "Raigad": ["Alibag", "Panvel", "Karjat", "Khopoli", "Mahad", "Pen", "Uran"],
    "Ratnagiri": ["Ratnagiri", "Chiplun", "Khed", "Dapoli", "Rajapur"],
    "Sangli": ["Sangli-Miraj-Kupwad", "Islampur", "Vita", "Tasgaon"],
    "Satara": ["Satara", "Karad", "Phaltan", "Wai", "Mahabaleshwar"],
    "Sindhudurg": ["Oros", "Sawantwadi", "Malvan", "Vengurla", "Kudal"],
    "Solapur": ["Solapur", "Pandharpur", "Barshi", "Akluj", "Sangola", "Kurduvadi"],
    "Thane": ["Thane", "Kalyan-Dombivli", "Navi Mumbai", "Mira-Bhayandar", "Ulhasnagar", "Ambernath", "Bhiwandi"],
    "Wardha": ["Wardha", "Hinganghat", "Arvi", "Pulgaon"],
    "Washim": ["Washim", "Karanja", "Risod", "Mangrulpir"],
    "Yavatmal": ["Yavatmal", "Pusad", "Wani", "Umarkhed", "Digras"]
  },
  "Manipur": {
    "Bishnupur": ["Bishnupur", "Moirang", "Nambol"],
    "Chandel": ["Chandel", "Moreh"],
    "Churachandpur": ["Churachandpur", "Tuibong"],
    "Imphal East": ["Imphal", "Porompat", "Heingang"],
    "Imphal West": ["Imphal", "Lamphelpat", "Wangoi"],
    "Jiribam": ["Jiribam"],
    "Kakching": ["Kakching", "Kakching Khunou"],
    "Kamjong": ["Kamjong"],
    "Kangpokpi": ["Kangpokpi", "Saitu Gamphazol"],
    "Noney": ["Noney"],
    "Pherzawl": ["Pherzawl"],
    "Senapati": ["Senapati", "Mao", "Maram"],
    "Tamenglong": ["Tamenglong"],
    "Tengnoupal": ["Tengnoupal"],
    "Thoubal": ["Thoubal", "Yairipok", "Wangjing"],
    "Ukhrul": ["Ukhrul", "Jessami"]
  },
  "Meghalaya": {
    "East Garo Hills": ["Williamnagar", "Rongjeng"],
    "East Jaintia Hills": ["Khliehriat", "Sutnga"],
    "East Khasi Hills": ["Shillong", "Sohra (Cherrapunjee)", "Mawryngkneng", "Mawsynram"],
    "Eastern West Khasi Hills": ["Mairang"],
    "North Garo Hills": ["Resubelpara"],
    "Ri Bhoi": ["Nongpoh", "Umsning", "Jirang"],
    "South Garo Hills": ["Baghmara"],
    "South West Garo Hills": ["Ampati"],
    "South West Khasi Hills": ["Mawkyrwat"],
    "West Garo Hills": ["Tura", "Dalu", "Phulbari"],
    "West Jaintia Hills": ["Jowai", "Amlarem"],
    "West Khasi Hills": ["Nongstoin", "Mawshynrut"]
  },
  "Mizoram": {
    "Aizawl": ["Aizawl", "Sairang", "Zemabawk", "Tlangnuam"],
    "Champhai": ["Champhai", "Zokhawthar"],
    "Hnahthial": ["Hnahthial"],
    "Khawzawl": ["Khawzawl"],
    "Kolasib": ["Kolasib", "Vairengte", "Bairabi"],
    "Lawngtlai": ["Lawngtlai"],
    "Lunglei": ["Lunglei", "Serkawn", "Hnahthial"],
    "Mamit": ["Mamit", "Kawrthah"],
    "Saiha": ["Saiha"],
    "Saitual": ["Saitual"],
    "Serchhip": ["Serchhip", "Thenzawl"]
  },
  "Nagaland": {
    "Chumoukedima": ["Chumoukedima", "Medziphema"],
    "Dimapur": ["Dimapur", "Purana Bazar", "Duncan Basti"],
    "Kiphire": ["Kiphire", "Pungro"],
    "Kohima": ["Kohima", "Chiephobozou", "Tseminyu"],
    "Longleng": ["Longleng"],
    "Mokokchung": ["Mokokchung", "Tuli", "Mangkolemba"],
    "Mon": ["Mon", "Aboi", "Tizit"],
    "Niuland": ["Niuland"],
    "Noklak": ["Noklak"],
    "Peren": ["Peren", "Jalukie"],
    "Phek": ["Phek", "Pfutsero", "Meluri"],
    "Shamator": ["Shamator"],
    "Tseminyu": ["Tseminyu"],
    "Tuensang": ["Tuensang", "Noklak", "Longkhim"],
    "Wokha": ["Wokha", "Bhandari"],
    "Zunheboto": ["Zunheboto", "Aghunato", "Pugkhoboto"]
  },
  "Odisha": {
    "Angul": ["Angul", "Talcher", "Athamallik", "Pallahara"],
    "Balangir": ["Balangir", "Titlagarh", "Kantabanji", "Patnagarh"],
    "Balasore": ["Balasore", "Jaleswar", "Soro", "Nilgiri"],
    "Bargarh": ["Bargarh", "Padampur", "Attabira", "Barpali"],
    "Bhadrak": ["Bhadrak", "Basudevpur", "Chandbali", "Dhamnagar"],
    "Boudh": ["Boudhgarh", "Kantamal", "Manamunda"],
    "Cuttack": ["Cuttack", "Choudwar", "Athagarh", "Banki", "Salipur"],
    "Deogarh": ["Debagarh", "Barkote", "Reamal"],
    "Dhenkanal": ["Dhenkanal", "Bhuban", "Kamakhyanagar", "Hindol"],
    "Gajapati": ["Paralakhemundi", "Kashinagar", "R.Udayagiri"],
    "Ganjam": ["Berhampur", "Chhatrapur", "Aska", "Bhanjanagar", "Hinjilicut"],
    "Jagatsinghpur": ["Jagatsinghpur", "Paradeep", "Rahama", "Tirtol"],
    "Jajpur": ["Jajpur Town", "Vyasanagar (Jajpur Road)", "Binjharpur", "Chandikhole"],
    "Jharsuguda": ["Jharsuguda", "Brajarajnagar", "Belpahar"],
    "Kalahandi": ["Bhawanipatna", "Kesinga", "Dharamgarh", "Junagarh"],
    "Kandhamal": ["Phulbani", "G.Udayagiri", "Baliguda"],
    "Kendrapara": ["Kendrapara", "Pattamundai", "Aul", "Rajnagar"],
    "Keonjhar": ["Kendujhar", "Anandapur", "Barbil", "Joda"],
    "Khordha": ["Bhubaneswar", "Khordha", "Jatni", "Banapur", "Begunia"],
    "Koraput": ["Koraput", "Jeypore", "Sunabeda", "Damanjodi", "Kotpad"],
    "Malkangiri": ["Malkangiri", "Balimela", "Chitrakonda"],
    "Mayurbhanj": ["Baripada", "Rairangpur", "Udala", "Karanjia"],
    "Nabarangpur": ["Nabarangpur", "Umerkote", "Raighar"],
    "Nayagarh": ["Nayagarh", "Khandapada", "Ranpur", "Odagaon"],
    "Nuapada": ["Nuapada", "Khariar", "Khariar Road"],
    "Puri": ["Puri", "Konark", "Pipili", "Nimapada"],
    "Rayagada": ["Rayagada", "Gunupur", "Muniguda"],
    "Sambalpur": ["Sambalpur", "Burla", "Hirakud", "Kuchinda", "Rairakhol"],
    "Sonepur": ["Sonepur", "Tarbha", "Birmaharajpur"],
    "Sundargarh": ["Rourkela", "Sundargarh", "Rajgangpur", "Birmitrapur", "Bonai"]
  },
  "Punjab": {
    "Amritsar": ["Amritsar", "Ajnala", "Rayya", "Majitha"],
    "Barnala": ["Barnala", "Tapa", "Bhadaur"],
    "Bathinda": ["Bathinda", "Rampura Phul", "Mauri", "Talwandi Sabo", "Sangat"],
    "Faridkot": ["Faridkot", "Kotkapura", "Jaitu"],
    "Fatehgarh Sahib": ["Sirhind-Fategarh", "Mandi Gobindgarh", "Amloh", "Khamanon"],
    "Fazilka": ["Fazilka", "Abohar", "Jalalabad"],
    "Ferozepur": ["Ferozepur", "Ferozepur Cantt", "Zira", "Guru Har Sahai"],
    "Gurdaspur": ["Gurdaspur", "Batala", "Dera Baba Nanak", "Dhariwal"],
    "Hoshiarpur": ["Hoshiarpur", "Dasuya", "Mukerian", "Garhdiwala", "Urmar Tanda"],
    "Jalandhar": ["Jalandhar", "Kartarpur", "Nakodar", "Phillaur", "Adampur"],
    "Kapurthala": ["Kapurthala", "Phagwara", "Sultanpur Lodhi", "Bholath"],
    "Ludhiana": ["Ludhiana", "Khanna", "Jagraon", "Samrala", "Sahnewal", "Mullanpur"],
    "Malerkotla": ["Malerkotla", "Amargarh"],
    "Mansa": ["Mansa", "Budhlada", "Bareta"],
    "Moga": ["Moga", "Dharamkot", "Baghapurana"],
    "Muktsar": ["Sri Muktsar Sahib", "Malout", "Gidderbaha"],
    "Pathankot": ["Pathankot", "Sujanpur"],
    "Patiala": ["Patiala", "Rajpura", "Nabha", "Samana", "Patran"],
    "Rupnagar": ["Rupnagar (Ropar)", "Nangal", "Anandpur Sahib", "Chamkaur Sahib"],
    "Sahibzada Ajit Singh Nagar": ["Mohali", "Kharar", "Zirakpur", "Dera Bassi"],
    "Sangrur": ["Sangrur", "Sunam", "Dhuri", "Ahmedgarh", "Lehragaga"],
    "Shahid Bhagat Singh Nagar": ["Nawanshahr", "Bangas", "Balachaur"],
    "Tarn Taran": ["Tarn Taran Sahib", "Patti", "Khadoor Sahib"]
  },
  "Rajasthan": {
    "Ajmer": ["Ajmer", "Beawar", "Kishangarh", "Pushkar", "Kekri"],
    "Alwar": ["Alwar", "Bhiwadi", "Tijara", "Behror", "Rajgarh"],
    "Anupgarh": ["Anupgarh", "Ghadshana"],
    "Balotra": ["Balotra", "Siwana"],
    "Banswara": ["Banswara", "Kushalgarh", "Ghatol"],
    "Baran": ["Baran", "Chhabra", "Antah"],
    "Barmer": ["Barmer", "Balotra", "Chohtan", "Sheo"],
    "Beawar": ["Beawar", "Masuda"],
    "Bharatpur": ["Bharatpur", "Deeg", "Bayana", "Kaman", "Weir"],
    "Bhilwara": ["Bhilwara", "Shahpura", "Asind", "Mandalgarh"],
    "Bikaner": ["Bikaner", "Nokha", "Gangashahar", "Dungargarh"],
    "Bundi": ["Bundi", "Lakheri", "Keshoraipatan"],
    "Chittorgarh": ["Chittorgarh", "Nimbahera", "Rawatbhata", "Bari Sadri"],
    "Churu": ["Churu", "Ratangarh", "Sujangarh", "Sardarshahar", "Rajgarh (Sadulpur)"],
    "Deeg": ["Deeg", "Kaman"],
    "Didwana-Kuchaman": ["Didwana", "Kuchaman City"],
    "Dholpur": ["Dholpur", "Bari", "Rajakhera"],
    "Dausa": ["Dausa", "Bandikui", "Lalsot"],
    "Dudu": ["Dudu"],
    "Dungarpur": ["Dungarpur", "Sagwara"],
    "Gangapur City": ["Gangapur City", "Wazirpur"],
    "Hanumangarh": ["Hanumangarh", "Nohar", "Bhadra", "Pilibanga"],
    "Jaipur": ["Jaipur", "Chomu", "Bagru", "Sanganer"],
    "Jaipur Rural": ["Kotputli", "Shahpura", "Bassi"],
    "Jaisalmer": ["Jaisalmer", "Pokaran"],
    "Jalore": ["Jalore", "Bhinmal", "Sanchore"],
    "Jhalawar": ["Jhalawar", "Jhalrapatan", "Bhawani Mandi"],
    "Jhunjhunu": ["Jhunjhunu", "Chirawa", "Nawalgarh", "Pilani", "Surajgarh"],
    "Jodhpur": ["Jodhpur", "Bilara", "Phalodi", "Piparcity"],
    "Jodhpur Rural": ["Luni", "Shergarh"],
    "Karauli": ["Karauli", "Hindaun City", "Todabhim"],
    "Kekri": ["Kekri", "Sarwar"],
    "Khairthal-Tijara": ["Khairthal", "Tijara"],
    "Kota": ["Kota", "Sangod", "Ramganj Mandi"],
    "Kotputli-Behror": ["Kotputli", "Behror"],
    "Nagaur": ["Nagaur", "Ladnun", "Merta City", "Makrana", "Deedwana"],
    "Neem Ka Thana": ["Neem Ka Thana", "Sri Madhopur"],
    "Pali": ["Pali", "Sojat", "Falna", "Bali", "Sadri"],
    "Phalodi": ["Phalodi", "Loha"],
    "Pratapgarh": ["Pratapgarh", "Chhoti Sadri"],
    "Rajsamand": ["Rajsamand", "Nathdwara", "Kankroli", "Amet"],
    "Salumbar": ["Salumbar"],
    "Sanchore": ["Sanchore"],
    "Sawai Madhopur": ["Sawai Madhopur", "Gangapur City", "Bamanwas"],
    "Shahpura": ["Shahpura", "Jahazpur"],
    "Sikar": ["Sikar", "Fatehpur", "Laxmangarh", "Sri Madhopur", "Ringas"],
    "Sirohi": ["Sirohi", "Mount Abu", "Abu Road", "Sheoganj"],
    "Sri Ganganagar": ["Sri Ganganagar", "Suratgarh", "Raisinghnagar", "Garsana"],
    "Tonk": ["Tonk", "Newai", "Deoli", "Malpura"],
    "Udaipur": ["Udaipur", "Fatehnagar", "Salumbar", "Bhinder"]
  },
  "Sikkim": {
    "Gangtok": ["Gangtok", "Ranipool", "Singtam"],
    "Gyalshing": ["Geyzing", "Pelling", "Yuksom"],
    "Mangan": ["Mangan", "Chungthang", "Lachung", "Lachen"],
    "Namchi": ["Namchi", "Jorethang", "Ravangla", "Melli"],
    "Pakyong": ["Pakyong", "Rongli", "Rangpo"],
    "Soreng": ["Soreng", "Nayabazar"]
  },
  "Tamil Nadu": {
    "Ariyalur": ["Ariyalur", "Jayamkondam"],
    "Chengalpattu": ["Chengalpattu", "Tambaram", "Pallavaram", "Madhuranthakam"],
    "Chennai": ["Chennai", "Nungambakkam", "T-Nagar", "Adyar", "Ambattur", "Mylapore"],
    "Coimbatore": ["Coimbatore", "Pollachi", "Mettupalayam", "Valparai", "Sulur"],
    "Cuddalore": ["Cuddalore", "Chidambaram", "Panruti", "Virudhachalam", "Neyveli"],
    "Dharmapuri": ["Dharmapuri", "Harur", "Pennagaram", "Palacode"],
    "Dindigul": ["Dindigul", "Palani", "Kodaikanal", "Oddanchatram", "Natham"],
    "Erode": ["Erode", "Gobichettipalayam", "Bhavani", "Perundurai"],
    "Kallakurichi": ["Kallakurichi", "Ulundurpet", "Sankarapuram"],
    "Kanchipuram": ["Kanchipuram", "Sriperumbudur", "Walajabad"],
    "Kanyakumari": ["Nagercoil", "Padmanabhapuram", "Kuzhithurai", "Colachel"],
    "Karur": ["Karur", "Kulithalai", "Pallapatti"],
    "Krishnagiri": ["Krishnagiri", "Hosur", "Denkanikottai", "Pochampalli"],
    "Madurai": ["Madurai", "Thirumangalam", "Melur", "Usilampatti"],
    "Mayiladuthurai": ["Mayiladuthurai", "Sirkazhi", "Tarangambadi"],
    "Nagapattinam": ["Nagapattinam", "Vedaranyam", "Velankanni"],
    "Namakkal": ["Namakkal", "Rasipuram", "Tiruchengode", "Komarapalayam"],
    "Nilgiris": ["Udhagamandalam (Ooty)", "Coonoor", "Gudalur", "Kotagiri"],
    "Perambalur": ["Perambalur"],
    "Pudukkottai": ["Pudukkottai", "Aranthangi", "Arimalam"],
    "Ramanathapuram": ["Ramanathapuram", "Rameswaram", "Paramakudi", "Keezhakarai"],
    "Ranipet": ["Ranipet", "Arakkonam", "Walajapet", "Arcot"],
    "Salem": ["Salem", "Attur", "Mettur", "Edappadi", "Omalur"],
    "Sivaganga": ["Sivaganga", "Karaikudi", "Devakottai", "Manamadurai"],
    "Tenkasi": ["Tenkasi", "Sankarankovil", "Kadayanallur", "Puliyangudi"],
    "Thanjavur": ["Thanjavur", "Kumbakonam", "Pattukkottai", "Adirampattinam"],
    "Theni": ["Theni Allinagaram", "Bodinayakanur", "Cumbum", "Periyakulam"],
    "Thoothukudi": ["Thoothukudi", "Kovilpatti", "Tiruchendur", "Kayalpattinam"],
    "Tiruchirappalli": ["Tiruchirappalli", "Srirangam", "Lalgudi", "Manapparai", "Thuraiyur"],
    "Tirunelveli": ["Tirunelveli", "Ambasamudram", "Vallioor", "Tenkasi"],
    "Tirupathur": ["Tirupathur", "Vaniyambadi", "Ambur"],
    "Tiruppur": ["Tiruppur", "Dharapuram", "Udumalaipettai", "Palladam"],
    "Tiruvallur": ["Tiruvallur", "Avadi", "Poonamallee", "Tiruttani"],
    "Tiruvannamalai": ["Tiruvannamalai", "Arani", "Vandavasi", "Cheyyar"],
    "Tiruvarur": ["Tiruvarur", "Mannargudi", "Thiruthuraipoondi"],
    "Vellore": ["Vellore", "Katpadi", "Gudiyatham", "Pernambut"],
    "Viluppuram": ["Viluppuram", "Tindivanam", "Gingee"],
    "Virudhunagar": ["Virudhunagar", "Sivakasi", "Rajapalayam", "Aruppukkottai", "Satur"]
  },
  "Telangana": {
    "Adilabad": ["Adilabad", "Utnoor", "Ichoda"],
    "Bhadradri Kothagudem": ["Kothagudem", "Bhadrachalam", "Palwancha", "Yellandu"],
    "Hanumakonda": ["Hanamkonda", "Kazipet", "Hasanparthy"],
    "Hyderabad": ["Hyderabad", "Secunderabad", "Banjara Hills", "Gachibowli", "Charminar"],
    "Jagtial": ["Jagtial", "Korutla", "Metpally"],
    "Jangaon": ["Jangaon", "Station Ghanpur"],
    "Jayashankar Bhupalpally": ["Bhupalpally", "Kataram"],
    "Jogulamba Gadwal": ["Gadwal", "Alampur"],
    "Kamareddy": ["Kamareddy", "Yellareddy", "Banswada"],
    "Karimnagar": ["Karimnagar", "Huzurabad", "Choppadandi"],
    "Khammam": ["Khammam", "Wyra", "Sathupally", "Madhira"],
    "Kumuram Bheem": ["Asifabad", "Kagaznagar"],
    "Mahabubabad": ["Mahabubabad", "Dornakal"],
    "Mahabubnagar": ["Mahabubnagar", "Jadcherla", "Devarkadra"],
    "Mancherial": ["Mancherial", "Bellampally", "Chennur"],
    "Medak": ["Medak", "Toopran", "Narsapur"],
    "Medchal-Malkajgiri": ["Malkajgiri", "Medchal", "Kukatpally", "Quthbullapur"],
    "Mulugu": ["Mulugu", "Eturnagaram", "Venkatapur"],
    "Nagarkurnool": ["Nagarkurnool", "Achampet", "Kollapur"],
    "Nalgonda": ["Nalgonda", "Miryalaguda", "Suryapet", "Devarakonda"],
    "Narayanpet": ["Narayanpet", "Kosgi"],
    "Nirmal": ["Nirmal", "Bhainsa", "Khanapur"],
    "Nizamabad": ["Nizamabad", "Armoor", "Bodhan", "Kamareddy"],
    "Peddapalli": ["Peddapalli", "Ramagundam", "Manthani"],
    "Rajanna Sircilla": ["Sircilla", "Vemulawada"],
    "Rangareddy": ["Rajendranagar", "Vikarabad", "Chevella", "Ibrahimpatnam", "Maheshwaram", "Shadnagar"],
    "Sangareddy": ["Sangareddy", "Patancheru", "Zaheerabad", "Narayankhed"],
    "Siddipet": ["Siddipet", "Gajwel", "Dubbak", "Husnabad"],
    "Suryapet": ["Suryapet", "Kodad", "Huzurnagar"],
    "Vikarabad": ["Vikarabad", "Tandur", "Pargi"],
    "Wanaparthy": ["Wanaparthy", "Kothakota"],
    "Warangal": ["Warangal", "Narsampet", "Wardhannapet"],
    "Yadadri Bhuvanagiri": ["Bhongir", "Alair", "Choutuppal"]
  },
  "Tripura": {
    "Dhalai": ["Ambassa", "Kamalpur", "Gandacharra"],
    "Gomati": ["Udaipur", "Amarpur", "Karbook"],
    "Khowai": ["Khowai", "Teliamura"],
    "Sipahijala": ["Bishalgarh", "Sonamura", "Jatrapur"],
    "Unakoti": ["Kailashahar", "Kumarghat"],
    "North Tripura": ["Dharmanagar", "Kanchanpur", "Panisagar"],
    "South Tripura": ["Belonia", "Santirbazar", "Sabroom"],
    "West Tripura": ["Agartala", "Ranirbazar", "Jirania", "Khayerpur", "Mandwi"]
  },
  "Uttar Pradesh": {
    "Agra": ["Agra", "Fatehpur Sikri", "Etmadpur", "Bah"],
    "Aligarh": ["Aligarh", "Khair", "Atrali", "Iglas"],
    "Ambedkar Nagar": ["Akbarpur", "Tanda", "Jalalpur"],
    "Amethi": ["Gauriganj", "Amethi", "Jagdishpur"],
    "Amroha": ["Amroha", "Gajraula", "Hasanpur"],
    "Auraiya": ["Auraiya", "Bidhuna", "Dibiyapur"],
    "Ayodhya": ["Ayodhya", "Faizabad", "Rudauli", "Milkipur"],
    "Azamgarh": ["Azamgarh", "Mubarakpur", "Lalganj", "Sagri"],
    "Baghpat": ["Baghpat", "Baraut", "Khekra"],
    "Bahraich": ["Bahraich", "Nanpara", "Kaiserganj"],
    "Ballia": ["Ballia", "Rasra", "Bansdih"],
    "Balrampur": ["Balrampur", "Utraula", "Tulsipur"],
    "Banda": ["Banda", "Atarra", "Baberu"],
    "Barabanki": ["Barabanki", "Fatehpur", "Ramsanehighat"],
    "Bareilly": ["Bareilly", "Aonla", "Baheri", "Faridpur"],
    "Basti": ["Basti", "Harraiya", "Rudhauli"],
    "Bhadohi": ["Gyanpur", "Bhadohi", "Gopiganj"],
    "Bijnor": ["Bijnor", "Najibabad", "Dhampur", "Chandpur"],
    "Budaun": ["Budaun", "Ujhani", "Sahaswan", "Dataganj"],
    "Bulandshahr": ["Bulandshahr", "Khurja", "Syana", "Anupshahar", "Sikandrabad"],
    "Chandauli": ["Chandauli", "Mughalsarai", "Chakkar"],
    "Chitrakoot": ["Karwi", "Mau"],
    "Deoria": ["Deoria", "Salempur", "Barhaj"],
    "Etah": ["Etah", "Jalesar", "Aliganj"],
    "Etawah": ["Etawah", "Bharthana", "Jaswantnagar"],
    "Farrukhabad": ["Farrukhabad", "Fatehgarh", "Kaimganj"],
    "Fatehpur": ["Fatehpur", "Bindki", "Khaga"],
    "Firozabad": ["Firozabad", "Shikohabad", "Tundla", "Sohag"],
    "Gautam Buddha Nagar": ["Noida", "Greater Noida", "Dadri", "Jewar", "Rabupura"],
    "Ghaziabad": ["Ghaziabad", "Loni", "Modinagar", "Muradnagar"],
    "Ghazipur": ["Ghazipur", "Saidpur", "Zamania", "Mohammadabad"],
    "Gonda": ["Gonda", "Colonelganj", "Tarabganj"],
    "Gorakhpur": ["Gorakhpur", "Sahjanwa", "Campierganj", "Chauri Chaura"],
    "Hamirpur": ["Hamirpur", "Maudaha", "Rath"],
    "Hapur": ["Hapur", "Garhmukteshwar", "Pilkhuwa"],
    "Hardoi": ["Hardoi", "Shahabad", "Sandila", "Bilgram"],
    "Hathras": ["Hathras", "Sikandra Rao", "Sadabad"],
    "Jalaun": ["Orai", "Kalpi", "Konch", "Jalaun"],
    "Jaunpur": ["Jaunpur", "Shahganj", "Machhlishand", "Mariahu"],
    "Jhansi": ["Jhansi", "Mauranipur", "Gursarai", "Ranipur", "Baragaon"],
    "Kannauj": ["Kannauj", "Chhibramau", "Tirwaganj"],
    "Kanpur Dehat": ["Akbarpur", "Rura", "Pukhrayan"],
    "Kanpur Nagar": ["Kanpur", "Bilhau", "Ghatampur"],
    "Kasganj": ["Kasganj", "Ganjdundwara", "Patiyali"],
    "Kaushambi": ["Manjhanpur", "Sirathu", "Chail"],
    "Kheri": ["Lakhimpur", "Gola Gokarannath", "Palanam", "Mohammadi"],
    "Kushinagar": ["Padrauna", "Hata", "Kasya"],
    "Lalitpur": ["Lalitpur", "Talbehat", "Mahroni"],
    "Lucknow": ["Lucknow", "Malihabad", "Bakshi Ka Talab", "Mohanlalganj"],
    "Maharajganj": ["Maharajganj", "Nautanwa", "Siswa Bazar"],
    "Mahoba": ["Mahoba", "Charkhari", "Kulpahar"],
    "Mainpuri": ["Mainpuri", "Karhal", "Bhongaon"],
    "Mathura": ["Mathura", "Vrindavan", "Kosi Kalan", "Chhata"],
    "Mau": ["Mau", "Maunath Bhanjan", "Madhuban", "Ghosi"],
    "Meerut": ["Meerut", "Sardhana", "Mawana", "Hastinapur"],
    "Mirzapur": ["Mirzapur", "Chunar", "Lalganj"],
    "Moradabad": ["Moradabad", "Thakurdwara", "Kanth", "Bilari"],
    "Muzaffarnagar": ["Muzaffarnagar", "Khatauli", "Budhana"],
    "Pilibhit": ["Pilibhit", "Bisalpur", "Puranpur"],
    "Pratapgarh": ["Pratapgarh", "Kunda", "Patti"],
    "Prayagraj": ["Prayagraj (Allahabad)", "Phulpur", "Handia", "Karchhana"],
    "Raebareli": ["Raebareli", "Lalganj", "Salon", "Maharajganj"],
    "Rampur": ["Rampur", "Bilaspur", "Suar", "Milak", "Shahabad"],
    "Saharanpur": ["Saharanpur", "Deoband", "Gangoh", "Behat"],
    "Sambhal": ["Sambhal", "Chandausi", "Babrala"],
    "Sant Kabir Nagar": ["Khalilabad", "Mehdawal"],
    "Shahjahanpur": ["Shahjahanpur", "Tilhar", "Powayan", "Jalalabad"],
    "Shamli": ["Shamli", "Kairana", "Thana Bhawan"],
    "Shravasti": ["Bhinga", "Ikauna"],
    "Siddharthnagar": ["Naugarh", "Bansi", "Itwa"],
    "Sitapur": ["Sitapur", "Laharpur", "Biswan", "Maholi", "Sidhauli"],
    "Sonbhadra": ["Robertsganj", "Obra", "Renukoot", "Pipri"],
    "Sultanpur": ["Sultanpur", "Kadipur", "Lambhua"],
    "Unnao": ["Unnao", "Purwa", "Safipur", "Bangarmau"],
    "Varanasi": ["Varanasi", "Ramnagar", "Pindra"]
  },
  "Uttarakhand": {
    "Almora": ["Almora", "Ranikhet", "Dwarahat", "Chaukhutia"],
    "Bageshwar": ["Bageshwar", "Garur", "Kapkot"],
    "Chamoli": ["Gopeshwar", "Joshimath", "Karnaprayag", "Badrinath"],
    "Champawat": ["Champawat", "Tanakpur", "Lohaghat"],
    "Dehradun": ["Dehradun", "Rishikesh", "Mussoorie", "Vikasnagar", "Chakrata", "Clement Town"],
    "Haridwar": ["Haridwar", "Roorkee", "Laksar", "Kankhal", "Manglaur"],
    "Nainital": ["Nainital", "Haldwani", "Ramnagar", "Bhimtal", "Lalkuan"],
    "Pauri Garhwal": ["Pauri", "Srinagar", "Kotdwar", "Lansdowne"],
    "Pithoragarh": ["Pithoragarh", "Dharchula", "Didihat", "Munsyari"],
    "Rudraprayag": ["Rudraprayag", "Kedarnath", "Ukhimath"],
    "Tehri Garhwal": ["New Tehri", "Narendra Nagar", "Chamba", "Devprayag"],
    "Udham Singh Nagar": ["Rudrapur", "Kashipur", "Khatima", "Pantnagar", "Gadarpur", "Kichha"],
    "Uttarkashi": ["Uttarkashi", "Barkot", "Bhatwari"]
  },
  "West Bengal": {
    "Alipurduar": ["Alipurduar", "Falakata", "Jaigaon"],
    "Bankura": ["Bankura", "Bishnupur", "Sonamukhi"],
    "Birbhum": ["Suri", "Bolpur", "Rampurhat", "Sainthia"],
    "Cooch Behar": ["Cooch Behar", "Dinhata", "Mathabhanga", "Tufanganj"],
    "Dakshin Dinajpur": ["Balurghat", "Gangarampur"],
    "Darjeeling": ["Darjeeling", "Siliguri", "Kurseong", "Mirik"],
    "Hooghly": ["Chinsurah", "Chandannagar", "Serampore", "Arambagh", "Uttarpara"],
    "Howrah": ["Howrah", "Bally", "Uluberia", "Amta"],
    "Jalpaiguri": ["Jalpaiguri", "Malbazar", "Dhupguri"],
    "Jhargram": ["Jhargram", "Gopiballavpur"],
    "Kalimpong": ["Kalimpong"],
    "Kolkata": ["Kolkata", "Salt Lake (Sector V)", "Newtown", "Alipore", "Park Street", "Garia"],
    "Malda": ["English Bazar (Malda)", "Old Malda", "Chanchal"],
    "Murshidabad": ["Baharampur", "Jiaganj-Azimganj", "Jangipur", "Kandi", "Dhuliyan"],
    "Nadia": ["Krishnanagar", "Kalyani", "Nabadwip", "Ranaghat", "Shantipur"],
    "North 24 Parganas": ["Barasat", "Barrackpore", "Bidhannagar", "Naihati", "Habra", "Basirhat"],
    "Paschim Bardhaman": ["Asansol", "Durgapur", "Raniganj", "Andal"],
    "Paschim Medinipur": ["Medinipur", "Kharagpur", "Ghatal", "Jhargram"],
    "Purba Bardhaman": ["Bardhaman", "Kalna", "Katwa", "Memari"],
    "Purba Medinipur": ["Tamluk", "Haldia", "Contai (Kanthi)", "Digha"],
    "Purulia": ["Purulia", "Adra", "Raghunathpur"],
    "South 24 Parganas": ["Alipore", "Baruipur", "Diamond Harbour", "Canning", "Sonarpur"],
    "Uttar Dinajpur": ["Raiganj", "Islampur", "Kaliaganj"]
  },
  "Andaman and Nicobar Islands": {
    "Nicobar": ["Car Nicobar", "Great Nicobar", "Nancowry"],
    "North and Middle Andaman": ["Mayabunder", "Rangat", "Diglipur", "Kadatala"],
    "South Andaman": ["Port Blair", "Garacharma", "Dollygunj"]
  },
  "Chandigarh": {
    "Chandigarh District": ["Chandigarh Capital", "Sector 17 Commercial", "Sector 35 Residential", "Sarangpur", "Manimajra"],
    "Mohali Border District": ["Mohali Border Block", "Phase 3B2 Sector", "Naya Gaon", "Khuda Alisher"]
  },
  "Dadra and Nagar Haveli and Daman and Diu": {
    "Dadra and Nagar Haveli": ["Silvassa", "Masat", "Rakholi", "Khanvel"],
    "Daman District": ["Daman", "Moti Daman", "Nani Daman", "Kachigam"],
    "Diu District": ["Diu", "Ghoghla", "Fudam"]
  },
  "Delhi": {
    "Central Delhi": ["Connaught Place", "Karol Bagh", "Pahar Ganj"],
    "East Delhi": ["Preet Vihar", "Mayur Vihar", "Shahdara", "Laxmi Nagar"],
    "New Delhi": ["Chanakyapuri", "Connaught Place", "Khan Market", "Delhi Cantonment"],
    "North Delhi": ["Sadar Bazar", "Kotwali", "Civil Lines"],
    "North East Delhi": ["Seelampur", "Shahdara", "Yamuna Vihar"],
    "North West Delhi": ["Saraswati Vihar", "Narela", "Model Town"],
    "Shahdara": ["Shahdara Town", "Seemapuri", "Rohtas Nagar"],
    "South Delhi": ["Saket", "Mehrauli", "Neb Sarai", "Hauz Khas", "Greater Kailash"],
    "South East Delhi": ["Defence Colony", "Kalkaji", "Lajpat Nagar"],
    "South West Delhi": ["Dwarka", "Vasant Vihar", "Palam", "Najafgarh"],
    "West Delhi": ["Rajouri Garden", "Punjabi Bagh", "Janakpuri", "Patel Nagar"]
  },
  "Jammu and Kashmir": {
    "Anantnag": ["Anantnag", "Bijbehara", "Pahalgam"],
    "Bandipora": ["Bandipora", "Gurez", "Sumbal"],
    "Baramulla": ["Baramulla", "Sopore", "Gulmarg", "Pattan"],
    "Budgam": ["Budgam", "Chadoora", "Beerwah"],
    "Doda": ["Doda", "Bhaderwah", "Thathri"],
    "Ganderbal": ["Ganderbal", "Kangan", "Lar"],
    "Jammu": ["Jammu", "Akhnoor", "R.S. Pura", "Gandhi Nagar", "Trikuta Nagar"],
    "Kathua": ["Kathua", "Hiranagar", "Basohli", "Billawar"],
    "Kishtwar": ["Kishtwar", "Padder"],
    "Kulgam": ["Kulgam", "Yaripora", "Devsar"],
    "Kupwara": ["Kupwara", "Handwara", "Karnah"],
    "Poonch": ["Poonch", "Surankote", "Mendhar"],
    "Pulwama": ["Pulwama", "Pampore", "Awantipora"],
    "Ramban": ["Ramban", "Banihal", "Batote"],
    "Reasi": ["Reasi", "Kattras", "Pouni"],
    "Samba": ["Samba", "Vijaypur", "Bari Brahmana"],
    "Shopian": ["Shopian"],
    "Srinagar": ["Srinagar", "Lal Chowk", "Dal Lake Boulevard", "Hazratbal"],
    "Udhampur": ["Udhampur", "Ramnagar", "Chenani"]
  },
  "Ladakh": {
    "Kargil": ["Kargil Bazaar Center", "Drass Valley", "Sankoo"],
    "Leh": ["Leh Main Bazar", "Choglamsar", "Shey", "Nobra"]
  },
  "Lakshadweep": {
    "Lakshadweep District": ["Kavaratti", "Minicoy", "Agatti", "Amini", "Kadmat", "Kalpeni"]
  },
  "Puducherry": {
    "Karaikal": ["Karaikal", "Neravy", "Tirunallar"],
    "Mahe": ["Mahe Town"],
    "Puducherry District": ["Pondicherry Town", "Oulgaret", "Auroville Outer", "Ariyankuppam"],
    "Yanam": ["Yanam Town"]
  }
};
